export const apiResponse = {
  businesses: [
    {
      id: "i50BEr4Pq6-D8tmsegmVyA",
      alias: "the-table-san-jose",
      name: "The Table",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/KMiVsvM886v1DpX7Ic9oxg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-table-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3442,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "salad",
          title: "Salad",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.308203,
        longitude: -121.901284,
      },
      transactions: ["delivery"],
      price: "$",
      location: {
        address1: "1110 Willow St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["1110 Willow St", "San Jose, CA 95125"],
      },
      phone: "+14086387911",
      display_phone: "(408) 638-7911",
      distance: 1712.3326119685419,
    },
    {
      id: "YwBw5RE9BCB1Kuq863t1hg",
      alias: "kings-fish-house-san-jose-san-jose",
      name: "King's Fish House - San Jose",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/CwJIeZ4L_JWpSdpokmOzpg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/kings-fish-house-san-jose-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1402,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.324143,
        longitude: -121.945867,
      },
      transactions: [],
      price: "$$$",
      location: {
        address1: "2855 Stevens Creek Blvd",
        address2: "Ste 1820",
        address3: null,
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: [
          "2855 Stevens Creek Blvd",
          "Ste 1820",
          "San Jose, CA 95128",
        ],
      },
      phone: "+16696993474",
      display_phone: "(669) 699-3474",
      distance: 5444.597485475577,
    },
    {
      id: "rjUOwXNxsg0tstFssAjfsQ",
      alias: "luna-mexican-kitchen-the-alameda-san-jose",
      name: "LUNA Mexican Kitchen - The Alameda",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/JjzG0auXHdUing7hHn7keQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/luna-mexican-kitchen-the-alameda-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 2342,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "vegetarian",
          title: "Vegetarian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33399,
        longitude: -121.915279,
      },
      transactions: ["pickup"],
      price: "$$",
      location: {
        address1: "1495 The Alameda",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95126",
        country: "US",
        state: "CA",
        display_address: ["1495 The Alameda", "San Jose, CA 95126"],
      },
      phone: "+14083202654",
      display_phone: "(408) 320-2654",
      distance: 3299.44931867476,
    },
    {
      id: "MlwoQuHxWozRFHeCeF7fZA",
      alias: "orchard-city-kitchen-campbell",
      name: "Orchard City Kitchen",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Bz--ib3cvKL1ZZp9JWl3Uw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/orchard-city-kitchen-campbell?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 4177,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.28820796640651,
        longitude: -121.93420216177606,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1875 S Bascom Ave",
        address2: "Ste 190",
        address3: "",
        city: "Campbell",
        zip_code: "95008",
        country: "US",
        state: "CA",
        display_address: ["1875 S Bascom Ave", "Ste 190", "Campbell, CA 95008"],
      },
      phone: "+14083405285",
      display_phone: "(408) 340-5285",
      distance: 5372.4403591283635,
    },
    {
      id: "6Bsqo2SLjtSn_cwwD-4RAg",
      alias: "black-sheep-brasserie-san-jose",
      name: "Black Sheep Brasserie",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/4n9holw-Zqbf4u7C5jmAhQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/black-sheep-brasserie-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 640,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "french",
          title: "French",
        },
        {
          alias: "brasseries",
          title: "Brasseries",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3069625,
        longitude: -121.8994391,
      },
      transactions: [],
      price: "$$$",
      location: {
        address1: "1202 Lincoln Ave",
        address2: "Ste 30",
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["1202 Lincoln Ave", "Ste 30", "San Jose, CA 95125"],
      },
      phone: "+14088167251",
      display_phone: "(408) 816-7251",
      distance: 1663.0564401834956,
    },
    {
      id: "wGBYKBR610I3K1_h4pHUrQ",
      alias: "firehouse-no-1-gastropub-san-jose",
      name: "Firehouse No.1 Gastropub",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/DZuE_RmnZ75_7RhNX2UCiA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/firehouse-no-1-gastropub-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1703,
      categories: [
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "pubs",
          title: "Pubs",
        },
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3363226652145,
        longitude: -121.893842965364,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "69 N San Pedro St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["69 N San Pedro St", "San Jose, CA 95110"],
      },
      phone: "+14082876969",
      display_phone: "(408) 287-6969",
      distance: 2329.5347770823396,
    },
    {
      id: "7NOpkoAUAGqMKEZgSu1QmA",
      alias: "a-slice-of-new-york-san-jose",
      name: "A Slice of New York",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/aTipilLBRg2sYIPF1eOf1A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/a-slice-of-new-york-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3272,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.3235243214913,
        longitude: -121.959063137967,
      },
      transactions: ["delivery"],
      price: "$",
      location: {
        address1: "3443 Stevens Creek Blvd",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95117",
        country: "US",
        state: "CA",
        display_address: ["3443 Stevens Creek Blvd", "San Jose, CA 95117"],
      },
      phone: "+14082475423",
      display_phone: "(408) 247-5423",
      distance: 6591.5760260939605,
    },
    {
      id: "ZYGMLW_biN_XMwdUo_90Jg",
      alias: "élyse-restaurant-san-jose-2",
      name: "Élyse Restaurant",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/8YCpbadULrjLZxfvP6Qc5w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/%C3%A9lyse-restaurant-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 454,
      categories: [
        {
          alias: "french",
          title: "French",
        },
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33363008882472,
        longitude: -121.88744268480657,
      },
      transactions: ["delivery", "restaurant_reservation"],
      price: "$$",
      location: {
        address1: "151 S 2nd St",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["151 S 2nd St", "San Jose, CA 95113"],
      },
      phone: "+14088992762",
      display_phone: "(408) 899-2762",
      distance: 1908.0212224768961,
    },
    {
      id: "fBCkn1-ZVVSF93nRMHnfHg",
      alias: "paper-plane-san-jose-2",
      name: "Paper Plane",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/CEzLkgkl5Tq3wynCVNGVXw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/paper-plane-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1528,
      categories: [
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3350126347807,
        longitude: -121.889442006445,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "72 S 1st St",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["72 S 1st St", "San Jose, CA 95113"],
      },
      phone: "+14087132625",
      display_phone: "(408) 713-2625",
      distance: 2086.5440782198098,
    },
    {
      id: "kOY-1i0jaW6Bb8as34sqwQ",
      alias: "the-grandview-restaurant-san-jose",
      name: "The Grandview Restaurant",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/gsy_3gmpd7f_Y-Rey8RAbw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-grandview-restaurant-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1844,
      categories: [
        {
          alias: "venues",
          title: "Venues & Event Spaces",
        },
        {
          alias: "steak",
          title: "Steakhouses",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3648315,
        longitude: -121.7640765,
      },
      transactions: ["restaurant_reservation", "pickup"],
      price: "$$$$",
      location: {
        address1: "15005 Mount Hamilton Rd",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95140",
        country: "US",
        state: "CA",
        display_address: ["15005 Mount Hamilton Rd", "San Jose, CA 95140"],
      },
      phone: "+14082518909",
      display_phone: "(408) 251-8909",
      distance: 11963.984768977882,
    },
    {
      id: "TANWKEUxyZvNnWu_Yv0ARg",
      alias: "the-breakfast-club-san-jose",
      name: "The Breakfast Club",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Yhf4z3CgYtlZNMyctn6tOw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-breakfast-club-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3623,
      categories: [
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "waffles",
          title: "Waffles",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.323197697534354,
        longitude: -121.9150064,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1432 W San Carlos St",
        address2: "Ste 80",
        address3: null,
        city: "San Jose",
        zip_code: "95126",
        country: "US",
        state: "CA",
        display_address: [
          "1432 W San Carlos St",
          "Ste 80",
          "San Jose, CA 95126",
        ],
      },
      phone: "+14085647150",
      display_phone: "(408) 564-7150",
      distance: 2750.601057968996,
    },
    {
      id: "PoqyugcuH71tkEwXnDcmYQ",
      alias: "mizu-sushi-bar-and-grill-san-jose",
      name: "Mizu Sushi Bar & Grill",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/Li5ts3s7VSi07KFjVtNYOg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mizu-sushi-bar-and-grill-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3138,
      categories: [
        {
          alias: "sushi",
          title: "Sushi Bars",
        },
        {
          alias: "japanese",
          title: "Japanese",
        },
        {
          alias: "korean",
          title: "Korean",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30805,
        longitude: -121.95056,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1035 S Winchester Blvd",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["1035 S Winchester Blvd", "San Jose, CA 95128"],
      },
      phone: "+14082607200",
      display_phone: "(408) 260-7200",
      distance: 5860.180238306413,
    },
    {
      id: "I-1l3unxDVaEOpUqSgNj1A",
      alias: "tostadas-san-jose",
      name: "Tostadas",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/eAPbEQgBv9UBZp9IXgucPQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/tostadas-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1431,
      categories: [
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "newmexican",
          title: "New Mexican Cuisine",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33935702614609,
        longitude: -121.88395663107825,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "304 E Santa Clara St",
        address2: "Ste A",
        address3: null,
        city: "San Jose",
        zip_code: "95112",
        country: "US",
        state: "CA",
        display_address: [
          "304 E Santa Clara St",
          "Ste A",
          "San Jose, CA 95112",
        ],
      },
      phone: "+16693424701",
      display_phone: "(669) 342-4701",
      distance: 2534.716156057644,
    },
    {
      id: "B3u5s5pun708ojwk_60ZDA",
      alias: "district-seven-kitchen-san-jose",
      name: "District Seven Kitchen",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/RH2pVjOzGUCCcEqUzsPozg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/district-seven-kitchen-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 149,
      categories: [
        {
          alias: "asianfusion",
          title: "Asian Fusion",
        },
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.331436,
        longitude: -121.857454,
      },
      transactions: ["delivery", "pickup"],
      price: "$$$",
      location: {
        address1: "979 Story Rd",
        address2: "Unit 7048",
        address3: "",
        city: "San Jose",
        zip_code: "95122",
        country: "US",
        state: "CA",
        display_address: ["979 Story Rd", "Unit 7048", "San Jose, CA 95122"],
      },
      phone: "+14086425771",
      display_phone: "(408) 642-5771",
      distance: 2945.8077163873054,
    },
    {
      id: "TQEfj1-QhyWCJ29u3l9Kjw",
      alias: "gen-korean-bbq-house-san-jose",
      name: "Gen Korean BBQ House",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/i0PPexcMvpmXY1y65lJ31g/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/gen-korean-bbq-house-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 7818,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "bbq",
          title: "Barbeque",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3872324410459,
        longitude: -121.885422354631,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "1628 Hostetter Rd",
        address2: "Ste F",
        address3: "",
        city: "San Jose",
        zip_code: "95131",
        country: "US",
        state: "CA",
        display_address: ["1628 Hostetter Rd", "Ste F", "San Jose, CA 95131"],
      },
      phone: "+14084772773",
      display_phone: "(408) 477-2773",
      distance: 7856.49136952106,
    },
    {
      id: "OeePb_OQIgCnt3nO53XEtA",
      alias: "claw-shack-san-jose",
      name: "Claw Shack",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/09J7eoBn26L_j-ekWNV72w/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/claw-shack-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1470,
      categories: [
        {
          alias: "cajun",
          title: "Cajun/Creole",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "chicken_wings",
          title: "Chicken Wings",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.3732322,
        longitude: -121.873416,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1696 Berryessa Rd",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95133",
        country: "US",
        state: "CA",
        display_address: ["1696 Berryessa Rd", "San Jose, CA 95133"],
      },
      phone: "+14086496741",
      display_phone: "(408) 649-6741",
      distance: 6334.255217632937,
    },
    {
      id: "Mvbq_Ai-QvIx7ceIUtC4pg",
      alias: "mariscos-costa-alegre-san-jose",
      name: "Mariscos Costa Alegre",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/kEJYTWSoboPibwp9a1PuTw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/mariscos-costa-alegre-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 579,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "sushi",
          title: "Sushi Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.35830364607693,
        longitude: -121.8905692,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "855 N13th St",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95112",
        country: "US",
        state: "CA",
        display_address: ["855 N13th St", "San Jose, CA 95112"],
      },
      phone: "+14082805014",
      display_phone: "(408) 280-5014",
      distance: 4665.404833488967,
    },
    {
      id: "zLViW6kDKNLIYsGkBCNorg",
      alias: "paesano-ristorante-italiano-san-jose",
      name: "Paesano Ristorante Italiano",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/oDYRK0KAZ7Le47ZhDDt0ag/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/paesano-ristorante-italiano-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1248,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.336166540678,
        longitude: -121.89867135144,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "350 W Julian St",
        address2: "Ste 1",
        address3: "",
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["350 W Julian St", "Ste 1", "San Jose, CA 95110"],
      },
      phone: "+14082179327",
      display_phone: "(408) 217-9327",
      distance: 2489.5832249207588,
    },
    {
      id: "sUrNF-1HaZ-kGRqzZljVEQ",
      alias: "the-cider-junction-san-jose-5",
      name: "The Cider Junction",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/_Ed3sZyd1p5otn2BK8fG1Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-cider-junction-san-jose-5?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 304,
      categories: [
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
        {
          alias: "cideries",
          title: "Cideries",
        },
        {
          alias: "comfortfood",
          title: "Comfort Food",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.310548,
        longitude: -121.895767,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "820 Willow St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["820 Willow St", "San Jose, CA 95125"],
      },
      phone: "+16692342751",
      display_phone: "(669) 234-2751",
      distance: 1164.0085569166704,
    },
    {
      id: "cCKea_ufuGcxI14fhe84vw",
      alias: "cha-cha-sushi-san-jose",
      name: "Cha Cha Sushi",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/zq_z2iHzoP8gCdgtuFMdNg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/cha-cha-sushi-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3854,
      categories: [
        {
          alias: "sushi",
          title: "Sushi Bars",
        },
        {
          alias: "japanese",
          title: "Japanese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.2758545677726,
        longitude: -121.852952245369,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "547 W Capitol Expy",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95136",
        country: "US",
        state: "CA",
        display_address: ["547 W Capitol Expy", "San Jose, CA 95136"],
      },
      phone: "+14082652416",
      display_phone: "(408) 265-2416",
      distance: 5344.071278185195,
    },
    {
      id: "QNzqZtNb_I1mcHAviE5zeQ",
      alias: "bibos-ny-pizza-san-jose",
      name: "Bibo's Ny Pizza",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/slNv72CZB3njkm6xSe0_yA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/bibos-ny-pizza-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1344,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.306477955952,
        longitude: -121.89160958914,
      },
      transactions: ["pickup"],
      price: "$$",
      location: {
        address1: "1431 Bird Ave",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["1431 Bird Ave", "San Jose, CA 95125"],
      },
      phone: "+14082179084",
      display_phone: "(408) 217-9084",
      distance: 1264.6251986624127,
    },
    {
      id: "kRxv3REQDh1tY2OfI8Z7uw",
      alias: "petiscos-san-jose",
      name: "Petiscos",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/TTRyBVAx3XRwkBXS89W4jg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/petiscos-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 346,
      categories: [
        {
          alias: "portuguese",
          title: "Portuguese",
        },
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.330018,
        longitude: -121.886354,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "399 S 1st St",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["399 S 1st St", "San Jose, CA 95113"],
      },
      phone: "+14083202884",
      display_phone: "(408) 320-2884",
      distance: 1504.685462417027,
    },
    {
      id: "jhX45-vpETLrx3DrCeXNoQ",
      alias: "adega-restaurant-san-jose",
      name: "ADEGA Restaurant",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/pM640CvW6e1SEVOtBhj53A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/adega-restaurant-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 583,
      categories: [
        {
          alias: "portuguese",
          title: "Portuguese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3510570887431,
        longitude: -121.858473403524,
      },
      transactions: [],
      price: "$$$$",
      location: {
        address1: "1614 Alum Rock Ave",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95116",
        country: "US",
        state: "CA",
        display_address: ["1614 Alum Rock Ave", "San Jose, CA 95116"],
      },
      phone: "+14089269075",
      display_phone: "(408) 926-9075",
      distance: 4496.002879207017,
    },
    {
      id: "7jidkejbcWaRsPhquW56lQ",
      alias: "le-papillon-san-jose",
      name: "Le Papillon",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/_VGkXA7Z_dlxi2jlRa98Lg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/le-papillon-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1179,
      categories: [
        {
          alias: "french",
          title: "French",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.31975,
        longitude: -121.97232,
      },
      transactions: [],
      price: "$$$$",
      location: {
        address1: "410 Saratoga Ave",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95129",
        country: "US",
        state: "CA",
        display_address: ["410 Saratoga Ave", "San Jose, CA 95129"],
      },
      phone: "+14082963730",
      display_phone: "(408) 296-3730",
      distance: 7719.426025280429,
    },
    {
      id: "IbOKhiMc9ciqgSjLBUnSIg",
      alias: "pho-ha-noi-san-jose-6",
      name: "Pho Ha Noi",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/Daf9IwA6OgtXrFEk_kxJFQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/pho-ha-noi-san-jose-6?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1445,
      categories: [
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3325078772,
        longitude: -121.858340912,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "969 Story Rd",
        address2: "Ste 6048",
        address3: null,
        city: "San Jose",
        zip_code: "95122",
        country: "US",
        state: "CA",
        display_address: ["969 Story Rd", "Ste 6048", "San Jose, CA 95122"],
      },
      phone: "+14082390888",
      display_phone: "(408) 239-0888",
      distance: 2951.1607238814936,
    },
    {
      id: "2cZKrmNPpFhEGsTOWDGuDw",
      alias: "ozumo-santana-row-san-jose-2",
      name: "Ozumo Santana Row",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ZSnQA6cj18qB3U8s4NJPpw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/ozumo-santana-row-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1362,
      categories: [
        {
          alias: "izakaya",
          title: "Izakaya",
        },
        {
          alias: "sushi",
          title: "Sushi Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3210174176298,
        longitude: -121.948078443517,
      },
      transactions: ["delivery", "pickup"],
      price: "$$$",
      location: {
        address1: "355 Santana Row",
        address2: "Ste 1010",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["355 Santana Row", "Ste 1010", "San Jose, CA 95128"],
      },
      phone: "+14088863090",
      display_phone: "(408) 886-3090",
      distance: 5596.7058089150105,
    },
    {
      id: "NTcYsSOMR7axKPehOPhwLA",
      alias: "bills-cafe-san-jose-10",
      name: "Bill's Cafe",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/-33iMBJUsBZKU-XtKH5tTQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/bills-cafe-san-jose-10?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 2305,
      categories: [
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.308366,
        longitude: -121.901722,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1115 Willow St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["1115 Willow St", "San Jose, CA 95125"],
      },
      phone: "+14082941125",
      display_phone: "(408) 294-1125",
      distance: 1735.3598807836956,
    },
    {
      id: "DvBxmtOxSl66U-Qb_Rkv1w",
      alias: "braise-willow-glen-san-jose",
      name: "Braise Willow Glen",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/IwwZ8B_3qu4E_yNnxf7WAA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/braise-willow-glen-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 400,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.30686,
        longitude: -121.90035,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1185 Lincoln Ave",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["1185 Lincoln Ave", "San Jose, CA 95125"],
      },
      phone: "+14082942919",
      display_phone: "(408) 294-2919",
      distance: 1731.3983510519909,
    },
    {
      id: "VUHVTQl8sWTAwtGcnfbRDw",
      alias: "island-taste-caribbean-grill-san-jose-2",
      name: "Island Taste Caribbean Grill",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/w0czBFAj_70hLlkOAXPT2A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/island-taste-caribbean-grill-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 167,
      categories: [
        {
          alias: "caribbean",
          title: "Caribbean",
        },
        {
          alias: "chicken_wings",
          title: "Chicken Wings",
        },
        {
          alias: "soulfood",
          title: "Soul Food",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33865,
        longitude: -121.88585,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "225 E Santa Clara St",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95112",
        country: "US",
        state: "CA",
        display_address: ["225 E Santa Clara St", "San Jose, CA 95112"],
      },
      phone: "+16692813554",
      display_phone: "(669) 281-3554",
      distance: 2446.6113518682273,
    },
    {
      id: "vtGDGnmACWtZPJR2i0q54A",
      alias: "jackies-place-san-jose",
      name: "Jackie's Place",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/cG4liINOZePo1m0s4e6Lnw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/jackies-place-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1030,
      categories: [
        {
          alias: "soulfood",
          title: "Soul Food",
        },
        {
          alias: "bbq",
          title: "Barbeque",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.352213,
        longitude: -121.902134,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "840 North 1st St",
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95112",
        country: "US",
        state: "CA",
        display_address: ["840 North 1st St", "San Jose, CA 95112"],
      },
      phone: "+14084904653",
      display_phone: "(408) 490-4653",
      distance: 4243.217993900624,
    },
    {
      id: "-A2EzuWuOhzGW2mkzr9sLg",
      alias: "the-city-fish-san-jose",
      name: "The City Fish",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/JVl-xxIIR1NPa6OXD7cxFA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/the-city-fish-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1237,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "fishnchips",
          title: "Fish & Chips",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33638,
        longitude: -121.88988,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "30 E Santa Clara St",
        address2: "Ste 140",
        address3: "",
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: [
          "30 E Santa Clara St",
          "Ste 140",
          "San Jose, CA 95113",
        ],
      },
      phone: "+14082933474",
      display_phone: "(408) 293-3474",
      distance: 2243.1654720874685,
    },
    {
      id: "28W6LDX-iXnSiim4ZClrYw",
      alias: "55-south-san-jose",
      name: "55 South",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/3WENV3DRIOSfQ6FWCQcXqA/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/55-south-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 714,
      categories: [
        {
          alias: "lounges",
          title: "Lounges",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.33503,
        longitude: -121.89013,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "55 S 1st St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["55 S 1st St", "San Jose, CA 95113"],
      },
      phone: "+14082886000",
      display_phone: "(408) 288-6000",
      distance: 2109.3086267688377,
    },
    {
      id: "vZ41QYMBQvtHgpAfw1IToQ",
      alias: "pizza-antica-san-jose",
      name: "Pizza Antica",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/L-wUGNzgH7coU7CfcxwVGg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/pizza-antica-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3195,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3217489749968,
        longitude: -121.948049744656,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "334 Santana Row",
        address2: "Ste 1065",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["334 Santana Row", "Ste 1065", "San Jose, CA 95128"],
      },
      phone: "+14085578373",
      display_phone: "(408) 557-8373",
      distance: 5601.915123859696,
    },
    {
      id: "jw7wkWmTX04fRYLcp9vlPQ",
      alias: "falafels-drive-in-san-jose",
      name: "Falafel's Drive-In",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/mHmUEG_gdQWBU0I7ymM07A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/falafels-drive-in-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 5142,
      categories: [
        {
          alias: "mideastern",
          title: "Middle Eastern",
        },
        {
          alias: "falafel",
          title: "Falafel",
        },
        {
          alias: "hotdogs",
          title: "Fast Food",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.323719276993586,
        longitude: -121.93508055499373,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "2301 Stevens Creek Blvd",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["2301 Stevens Creek Blvd", "San Jose, CA 95128"],
      },
      phone: "+14082947886",
      display_phone: "(408) 294-7886",
      distance: 4496.084042426032,
    },
    {
      id: "qHOhugxuQStt3eOK2SCqrA",
      alias: "bills-cafe-san-jose-25",
      name: "Bill's Cafe",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/XUS57sY4C2BUUjiP2-vLqw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/bills-cafe-san-jose-25?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 2289,
      categories: [
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.34303,
        longitude: -121.92846,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "2089 The Alameda",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95126",
        country: "US",
        state: "CA",
        display_address: ["2089 The Alameda", "San Jose, CA 95126"],
      },
      phone: "+14082449085",
      display_phone: "(408) 244-9085",
      distance: 4836.2464418181335,
    },
    {
      id: "CTbh1zm-SsVVEmSxVexaTA",
      alias: "little-wine-house-san-jose",
      name: "Little Wine House",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/LtEDLuzoDiY0ujxLRvY0ag/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/little-wine-house-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 53,
      categories: [
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
        {
          alias: "beerbar",
          title: "Beer Bar",
        },
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 37.33574,
        longitude: -121.89884,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "350 W Julian St",
        address2: "Bldg 4",
        address3: "",
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["350 W Julian St", "Bldg 4", "San Jose, CA 95110"],
      },
      phone: "+14084718039",
      display_phone: "(408) 471-8039",
      distance: 2460.95007796801,
    },
    {
      id: "HIumpta3AS8WwFDEC0Hsnw",
      alias: "abve-the-basics-san-jose-3",
      name: "ABVE The Basics",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/HAcevrpQYPAhMoYb_l5Q3A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/abve-the-basics-san-jose-3?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 235,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.33478397714884,
        longitude: -121.8887984955349,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: null,
        address2: null,
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["San Jose, CA 95125"],
      },
      phone: "+16692268050",
      display_phone: "(669) 226-8050",
      distance: 2051.5787611829796,
    },
    {
      id: "MRlHo4kxMHRVj5iUyvxZQA",
      alias: "yard-house-san-jose-4",
      name: "Yard House",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/EQqRjqYV6fbZDYM1GX6WuQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/yard-house-san-jose-4?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 4172,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "vegetarian",
          title: "Vegetarian",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 3.5,
      coordinates: {
        latitude: 37.3229817029011,
        longitude: -121.947494338623,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "300 Santana Row",
        address2: "Ste 101",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["300 Santana Row", "Ste 101", "San Jose, CA 95128"],
      },
      phone: "+14082419273",
      display_phone: "(408) 241-9273",
      distance: 5568.879787063705,
    },
    {
      id: "3eKhFdXHvne3_YVjxfrTGQ",
      alias: "fogo-de-chao-brazilian-steakhouse-san-jose-6",
      name: "Fogo de Chao Brazilian Steakhouse",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/DWFemT5KPCv36LW1MUnpDw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/fogo-de-chao-brazilian-steakhouse-san-jose-6?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3488,
      categories: [
        {
          alias: "brazilian",
          title: "Brazilian",
        },
        {
          alias: "steak",
          title: "Steakhouses",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3202585632998,
        longitude: -121.949787738762,
      },
      transactions: ["delivery", "pickup"],
      price: "$$$",
      location: {
        address1: "377 Santana Row",
        address2: "Ste 1090",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["377 Santana Row", "Ste 1090", "San Jose, CA 95128"],
      },
      phone: "+14082447001",
      display_phone: "(408) 244-7001",
      distance: 5740.682553656406,
    },
    {
      id: "HXMMPwezFi3lgR-o9crECQ",
      alias: "haberdasher-san-jose",
      name: "Haberdasher",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/5Fyyss1udz8uNjILtfdsfg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/haberdasher-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 613,
      categories: [
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.32987887222109,
        longitude: -121.88655672883556,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "43 W San Salvador St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["43 W San Salvador St", "San Jose, CA 95113"],
      },
      phone: "+14087927356",
      display_phone: "(408) 792-7356",
      distance: 1485.1008485316488,
    },
    {
      id: "kgOfzKLREO-x935D-flk2Q",
      alias: "dia-de-pesca-san-jose-4",
      name: "Dia de Pesca",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/NCPlvVvwYu373_qwR8l2Ig/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/dia-de-pesca-san-jose-4?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1794,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.324569,
        longitude: -121.932301,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "55 N Bascom Ave",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95128",
        country: "US",
        state: "CA",
        display_address: ["55 N Bascom Ave", "San Jose, CA 95128"],
      },
      phone: "+14082873722",
      display_phone: "(408) 287-3722",
      distance: 4272.997615655284,
    },
    {
      id: "QJJd1N0QjQgUtv4hIuhqGg",
      alias: "taurinus-brazilian-steakhouse-san-jose-2",
      name: "Taurinus Brazilian Steakhouse",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/gUqj6xQJgOWcRFbTYKWEWg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/taurinus-brazilian-steakhouse-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1176,
      categories: [
        {
          alias: "brazilian",
          title: "Brazilian",
        },
        {
          alias: "steak",
          title: "Steakhouses",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.333145,
        longitude: -121.892216,
      },
      transactions: ["delivery", "restaurant_reservation", "pickup"],
      price: "$$$$",
      location: {
        address1: "167 W San Fernando St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95113",
        country: "US",
        state: "CA",
        display_address: ["167 W San Fernando St", "San Jose, CA 95113"],
      },
      phone: "+14082940110",
      display_phone: "(408) 294-0110",
      distance: 1948.514561801975,
    },
    {
      id: "rcAuEGObdU6wf4QcBJNg6Q",
      alias: "san-pedro-square-market-san-jose",
      name: "San Pedro Square Market",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/tKdG23NlBktE64c9zbqd-A/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/san-pedro-square-market-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1263,
      categories: [
        {
          alias: "venues",
          title: "Venues & Event Spaces",
        },
        {
          alias: "musicvenues",
          title: "Music Venues",
        },
        {
          alias: "food_court",
          title: "Food Court",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3366485,
        longitude: -121.8941835,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "87 N San Pedro St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["87 N San Pedro St", "San Jose, CA 95110"],
      },
      phone: "",
      display_phone: "",
      distance: 2373.8023922286266,
    },
    {
      id: "ozgoYrwfc4te-teWmegM_g",
      alias: "udon-mugizo-san-jose-san-jose",
      name: "Udon Mugizo - San Jose",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/2fS4QYadN_qCwGjuLc5w4Q/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/udon-mugizo-san-jose-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 501,
      categories: [
        {
          alias: "japanese",
          title: "Japanese",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.30656,
        longitude: -121.9776,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1072 Saratoga Ave",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95129",
        country: "US",
        state: "CA",
        display_address: ["1072 Saratoga Ave", "San Jose, CA 95129"],
      },
      phone: "+14083202291",
      display_phone: "(408) 320-2291",
      distance: 8259.094193437304,
    },
    {
      id: "xjMeVFpOFtGsSqgWYMs9Qg",
      alias: "zona-rosa-san-jose",
      name: "Zona Rosa",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/-0K0DsDYDZcdD70DMINAZQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/zona-rosa-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1444,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3330684770691,
        longitude: -121.914127461814,
      },
      transactions: ["delivery", "restaurant_reservation", "pickup"],
      price: "$$",
      location: {
        address1: "1411 The Alameda",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95126",
        country: "US",
        state: "CA",
        display_address: ["1411 The Alameda", "San Jose, CA 95126"],
      },
      phone: "+14082751411",
      display_phone: "(408) 275-1411",
      distance: 3159.0355284951443,
    },
    {
      id: "jfMK6n5Mln7ilco6r2YXoA",
      alias: "qpot-san-jose-2",
      name: "QPOT",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/n2flHH6CC6OVTNULFDLLDQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/qpot-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 3705,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "hotpot",
          title: "Hot Pot",
        },
        {
          alias: "bbq",
          title: "Barbeque",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.305813,
        longitude: -121.812039,
      },
      transactions: ["pickup"],
      price: "$$",
      location: {
        address1: "1610 E Capitol Expy",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95121",
        country: "US",
        state: "CA",
        display_address: ["1610 E Capitol Expy", "San Jose, CA 95121"],
      },
      phone: "+16692343095",
      display_phone: "(669) 234-3095",
      distance: 6565.816895646217,
    },
    {
      id: "UPjhJoqpbJr0u8mvTOxneQ",
      alias: "sj-omogari-san-jose-3",
      name: "SJ Omogari",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Q-R5F0ZyM0STS_r03pI_WQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/sj-omogari-san-jose-3?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 2392,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "soup",
          title: "Soup",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.348433,
        longitude: -121.895124,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "154 Jackson St",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95112",
        country: "US",
        state: "CA",
        display_address: ["154 Jackson St", "San Jose, CA 95112"],
      },
      phone: "+14082888134",
      display_phone: "(408) 288-8134",
      distance: 3652.6961387694555,
    },
    {
      id: "AUo3AVgAiEfl9icvM57aaA",
      alias: "district-san-jose-san-jose",
      name: "District - San Jose",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/vtrECsbd4BIxuaq8yy9gRw/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/district-san-jose-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 445,
      categories: [
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
        {
          alias: "whiskeybars",
          title: "Whiskey Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.336178007464,
        longitude: -121.893876187673,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "65 N San Pedro St",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["65 N San Pedro St", "San Jose, CA 95110"],
      },
      phone: "+16692925252",
      display_phone: "(669) 292-5252",
      distance: 2315.371573057313,
    },
    {
      id: "ZMdteLcR8y2N-oJAd9cmEg",
      alias: "souvlakis-greek-skewers-san-jose",
      name: "Souvlaki's Greek Skewers",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/z4r8S3Ib8husncAgEa5Ozg/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/souvlakis-greek-skewers-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 1129,
      categories: [
        {
          alias: "greek",
          title: "Greek",
        },
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.3092867427984,
        longitude: -121.887104945135,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "577 W Alma Ave",
        address2: "",
        address3: "",
        city: "San Jose",
        zip_code: "95125",
        country: "US",
        state: "CA",
        display_address: ["577 W Alma Ave", "San Jose, CA 95125"],
      },
      phone: "+14082891452",
      display_phone: "(408) 289-1452",
      distance: 831.1353604768171,
    },
    {
      id: "djU4sbbnEzbUOB2uJy5MjA",
      alias: "olla-cocina-san-jose-2",
      name: "Olla",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/q_OzHS59Mz0_IMp0JXyKCQ/o.jpg",
      is_closed: false,
      url: "https://www.yelp.com/biz/olla-cocina-san-jose-2?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
      review_count: 753,
      categories: [
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "tacos",
          title: "Tacos",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.3354307,
        longitude: -121.8933631,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "17 N San Pedro St",
        address2: "",
        address3: null,
        city: "San Jose",
        zip_code: "95110",
        country: "US",
        state: "CA",
        display_address: ["17 N San Pedro St", "San Jose, CA 95110"],
      },
      phone: "+14086067999",
      display_phone: "(408) 606-7999",
      distance: 2221.886674532541,
    },
  ],
  total: 5400,
  region: {
    center: {
      longitude: -121.88507080078125,
      latitude: 37.31648115417059,
    },
  },
};
