export const singleCard = {
  id: "rjUOwXNxsg0tstFssAjfsQ",
  alias: "luna-mexican-kitchen-the-alameda-san-jose",
  name: "LUNA Mexican Kitchen - The Alameda",
  image_url:
    "https://s3-media1.fl.yelpcdn.com/bphoto/JjzG0auXHdUing7hHn7keQ/o.jpg",
  is_claimed: true,
  is_closed: false,
  url: "https://www.yelp.com/biz/luna-mexican-kitchen-the-alameda-san-jose?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
  phone: "+14083202654",
  display_phone: "(408) 320-2654",
  review_count: 2342,
  categories: [
    {
      alias: "mexican",
      title: "Mexican",
    },
    {
      alias: "breakfast_brunch",
      title: "Breakfast & Brunch",
    },
    {
      alias: "vegetarian",
      title: "Vegetarian",
    },
  ],
  rating: 4.0,
  location: {
    address1: "1495 The Alameda",
    address2: "",
    address3: null,
    city: "San Jose",
    zip_code: "95126",
    country: "US",
    state: "CA",
    display_address: ["1495 The Alameda", "San Jose, CA 95126"],
    cross_streets: "",
  },
  coordinates: {
    latitude: 37.33399,
    longitude: -121.915279,
  },
  photos: [
    "https://s3-media1.fl.yelpcdn.com/bphoto/JjzG0auXHdUing7hHn7keQ/o.jpg",
    "https://s3-media4.fl.yelpcdn.com/bphoto/vs_mNhVvxbuREFkLbH8A2A/o.jpg",
    "https://s3-media3.fl.yelpcdn.com/bphoto/em0WYcE5FoREmHGMLR1zcw/o.jpg",
  ],
  price: "$$",
  hours: [
    {
      open: [
        {
          is_overnight: false,
          start: "0900",
          end: "2100",
          day: 0,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2100",
          day: 1,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2100",
          day: 2,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2100",
          day: 3,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2200",
          day: 4,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2200",
          day: 5,
        },
        {
          is_overnight: false,
          start: "0900",
          end: "2100",
          day: 6,
        },
      ],
      hours_type: "REGULAR",
      is_open_now: false,
    },
  ],
  transactions: ["pickup"],
  messaging: {
    url: "https://www.yelp.com/raq/rjUOwXNxsg0tstFssAjfsQ?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=W1dNi6Ziy5O0z-dk2LOQow#popup%3Araq",
    use_case_text: "Message the Business",
  },
  special_hours: [
    {
      date: "2023-11-23",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
    {
      date: "2023-11-24",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
    {
      date: "2023-12-24",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
    {
      date: "2023-12-25",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
    {
      date: "2023-12-25",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
    {
      date: "2023-12-26",
      is_closed: true,
      start: null,
      end: null,
      is_overnight: null,
    },
  ],
};
